### ISSUE TITLE
Basic movement

### ISSUE THREAD

**Issue by srlafortune** [ludum-dare/ld-44#4]
Need basic movement working for the player character

**Comment by Shunderpooch** [comment]
How are you planning on doing movement? Are we thinking grounded, like on a side scrolling space, attacked from all sides and in the center, or something else? Also, do we have a player entity? If we don't have that I would argue we should focus on that first. @srlafortune

**Comment by Shunderpooch** [comment]
We're moving the camera with the player ideally, so the map will side scroll as we fight through enemies. 

[Phaser Camera Documentation](https://photonstorm.github.io/phaser3-docs/Phaser.Cameras.Scene2D.Camera.html)

**Comment by Shunderpooch** [comment]
[Mario Platformer Example](https://gamedevacademy.org/how-to-make-a-mario-style-platformer-with-phaser-3/)
